// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDazbIQ7r57bVg56uG9YdKjeeudQ40QL-4',
    appId: '1:277280999630:web:eb7bab2bead1965085689f',
    messagingSenderId: '277280999630',
    projectId: 'moneymanagement-7fdb9',
    authDomain: 'moneymanagement-7fdb9.firebaseapp.com',
    storageBucket: 'moneymanagement-7fdb9.firebasestorage.app',
    measurementId: 'G-36C44YH3R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRg60ttcsIoY03wC0jX9SZ9X0njNWjVU',
    appId: '1:277280999630:android:8a43f42c81f3c06385689f',
    messagingSenderId: '277280999630',
    projectId: 'moneymanagement-7fdb9',
    storageBucket: 'moneymanagement-7fdb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4D8i2mRTVHgqiLP1pTo8hP0ZSbpCsbg',
    appId: '1:277280999630:ios:e38323b2d688752885689f',
    messagingSenderId: '277280999630',
    projectId: 'moneymanagement-7fdb9',
    storageBucket: 'moneymanagement-7fdb9.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4D8i2mRTVHgqiLP1pTo8hP0ZSbpCsbg',
    appId: '1:277280999630:ios:e38323b2d688752885689f',
    messagingSenderId: '277280999630',
    projectId: 'moneymanagement-7fdb9',
    storageBucket: 'moneymanagement-7fdb9.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDazbIQ7r57bVg56uG9YdKjeeudQ40QL-4',
    appId: '1:277280999630:web:f255051071b3ec2b85689f',
    messagingSenderId: '277280999630',
    projectId: 'moneymanagement-7fdb9',
    authDomain: 'moneymanagement-7fdb9.firebaseapp.com',
    storageBucket: 'moneymanagement-7fdb9.firebasestorage.app',
    measurementId: 'G-RM7FET0F3W',
  );
}
